version: '3.8'
services:
  proxymanager:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: "1"
        NODE_VERSION: "16"
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
volumes:
  postgres:
  redis:
networks:
  default:
    name: dev